name: Get SQL response

on:
  push:
    paths:
      - 'request.sql'

jobs:
  get-response:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get -y install default-mysql-client

      - name: Get SQL response
        run: |
            mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam < request.sql
            
